### ISSUE TITLE
Looped bot messages.

### ISSUE THREAD

**Issue by Daber2012** [dontgiveafish/hryvna-today-telegram#1]
Yestarday it not responding on commands.
Today it start to respond on 3 commands every 1-3 minutes.
https://monosnap.com/file/sTOPjG52PAcGux7t77MrzKwCLA3mfF
https://monosnap.com/file/roWWhwAILUAj6FmDmjv6tI6ngfdPOJ
"Stop and block" bot do not help.

**Comment by abagayev** [comment]
Thanks for the report! I've finally reproduced this error, will fix in a few days.

**Comment by neepl** [comment]
Same problem. Started about 1 week ago.

**Comment by abagayev** [comment]
Fixed with the last commit

**Comment by Daber2012** [comment]
Thank you.

пт, 11 груд. 2020, 23:24 користувач Anton Bagaiev <notifications@github.com>
пише:
